### ISSUE TITLE
ACE AUTOLUTION - FEED BACK

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#1]
PHP ACC TEAM,

FIX THE BELOW FEED BACK.
![issue_08092015](https://cloud.githubusercontent.com/assets/9882142/9728202/eea122be-5638-11e5-8833-05373b394678.png)

**Comment by Archana20** [comment]
Please fix issues in Ace and Premium Accounting .. Updated in SS please check and fix.

https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1413317958

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

 CR: When a JS is created, it shd be retrievable/selectable/free field w AUTO suggest option from the LB under the INVOICE creation, i.e, show the list of JS under the ADD INVOICE form.

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

1. ACE INV

CR:
JS no - Auito comoplete
CUST - Quick ADD
Store location - remve the field

dont change others, complete the INV

**Comment by DHANDAPANISATTANATHAN** [comment]
Credit Term - Quick ADD

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

Reduce the ace inv font size in pdf.

**Comment by DHANDAPANISATTANATHAN** [comment]
OWNER: SQL TEAM

change location to Department in the below err msg

LOCATION INSERTED SUCCESSFULLY

**Comment by DHANDAPANISATTANATHAN** [comment]
fix the below issue immediately

![defect](https://cloud.githubusercontent.com/assets/9882142/10709440/24f4c2f2-7a61-11e5-82f7-872c81f17d2c.png)

**Comment by SasikalaDjeasankar** [comment]
##### Status:Closed
