### ISSUE TITLE
issue found on 5/12/2015

### ISSUE THREAD

**Issue by RAJALAKSHMIRAJKUMAR** [SSOMENSREPO/ACE-AUTOLUTION#12]
# defect owner : ace team
1.Customer exchange form not working properly
2.Purchase oreder & purchase view form for approval login id not showing but values saved in db 
3.Income edit form payment details not showing properly
4.Remove pdf btn in income form
5.Expense lastly inserted record need to cum first in data table
6.Expense copy not working
7.Delete btn need to remove in journal entry form

**Comment by SasikalaDjeasankar** [comment]
Fixed above all issues and uploaded in GCE.

**Comment by DHANDAPANISATTANATHAN** [comment]
CR:

Create one form in setting to enter smtp configuration.

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
MENU ADDED FOR CONFIG FORM & UPDATED THIS MENU IN ALL ACE DB & ACE EMPTY DB

Status : **Done**

**Comment by SasikalaDjeasankar** [comment]
Issue #12 
#### Status:Closed
