### ISSUE TITLE
issue found on 7/12/2015

### ISSUE THREAD

**Issue by RAJALAKSHMIRAJKUMAR** [SSOMENSREPO/ACE-AUTOLUTION#13]
Defect owner : **ACE TEAM**

1.Need to load all curreny & set default currenty as singapore in company information form
2.Need to load all curreny & set default currenty as singapore in invoice & credit note customization form
3.Searching date range no data means total income showing null in income by customer form
4.Searching date range no data means total expense showing null in expense by ventor form
5.purchase debit note date range search not working properly

**Comment by KAVINKARNAN** [comment]
status: Done
Point no: 3,4,5 fixed.

**Comment by BalachandarNatarajan** [comment]
status:done
Point No:1 fixed.

**Comment by SasikalaDjeasankar** [comment]
Issue #13 
##### Status:Closed
