### ISSUE TITLE
DEFECT IN ACE MULTIROW

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#15]
@SasikalaDjeasankar 

In Ace inv multirow not working properly.

Finally Client want to add CAT,SUB CAT IN Service also.

So if we remove first row. Script validation not working.

Include Others in CAT, SubCAT also .First row no need to remove.

Check in all ACE FORM AND FIX

FIX AND DELY!

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar  & @safiyullahmohideen 

INV multi row shld validate like EI PAYMENT multi row.

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar  & @safiyullahmohideen 

# FEED BACK - fix and dely quickly

1.show others in server in first row
2.include can remove first row.
3. After removing any row. + button can click.restrict it.
4.Check if NaN price. Restrict + Button

**Comment by SasikalaDjeasankar** [comment]
Above feedback points are fixed.

##### Status :Closed
