### ISSUE TITLE
ACCOUNTING PROJECT DEFECT - 17/12/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#16]
# BOTH ACE AND PP

# Fix the below in Both project multirow forms. QUOTATION,CONFIRM,INV,PURCHASE.....

1. Add product in pop up. hide/ read only subcategory.bcz in multirow they select cat and subcat,
2. After quick add in product, shld load in DDL. now after refresh only showing
3.Out of range error came.My SQL 5.7. shld restrict all amt field max digit.otherwise sent customized error msg from DB.

**Comment by DHANDAPANISATTANATHAN** [comment]
3. ACE PRODUCT FORM I CANNT SEE THE IMAGE IN DT.

# Point 2 : PUT ON HOLD

**Comment by DHANDAPANISATTANATHAN** [comment]
# OWNER: SKL & RL


1.PAYEMENT FORM ISSUE:

In invoice,purchase,exp and income not roll back Change in both side.


2.Case B in ace doc

3.Dont send empty to sp for all decimal/float.( BCZ OF MySQL 5.7)

FIX AND DELY TODAY!

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
Form side rollback not working properly while calling multiple sp at a time. By using save point this is issue fixed. Need to implement in form.

**Comment by SasikalaDjeasankar** [comment]
1.Because for SP, rollback not working in form side, now they changed SP with savepoint.

In previously they used Exit handler inside SP for this only rollback not working.

In form side need to implement savepoint for Invoice,Purchase,Expense and Income forms.

2. Fixed Case B on Friday(18-12-2015) and updated script in DEV.

3.In previous version we didnt get this type of error after changed version only we are getting this error. If this one important to deliver this project means need to implement for all forms need to check and change.

**Comment by DHANDAPANISATTANATHAN** [comment]
@RAJALAKSHMIRAJKUMAR  @SasikalaDjeasankar 

Tmrw  morning before 10.30 am all shld fix in ACE!

**Comment by SasikalaDjeasankar** [comment]
1.IMPLEMENTED SAVEPOINT ROLLBACK FOR PAYMENT ISSUE IN  BELOW LISTED FORMS.
           A) INVOICE
           B)PURCHASE
           C)EXPENSE
           D)INCOME


UPDATED SCRIPT IN DEV SERVER

#### STATUS :DONE

**Comment by DHANDAPANISATTANATHAN** [comment]
@RAJALAKSHMIRAJKUMAR 

After roll back. i cannt see the consecutive inv now.Roll back PK ID , All JS, INV, PURCHASE SHLD IN CONTINUOUS ORDER.

@SasikalaDjeasankar 

In Ace Multirow.Refer the below image. form showing cat, sub cat service select, service desc has value. i cant save, but DB it saved others. Fix it!




![image](https://cloud.githubusercontent.com/assets/9882142/11951278/c06fd078-a8b5-11e5-90b0-ff34cf14ea2a.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
# RE - OPEN: ACC TEAM.

# mPDF error: IMAGE Error (../public/images/ACE_logo.png): GD library required for PNG image (alpha channel)

**Comment by DHANDAPANISATTANATHAN** [comment]
# CR

@SasikalaDjeasankar 

In invoice remarks while using special character. Edit inv not loading, Allow this and dely

**Comment by SasikalaDjeasankar** [comment]
Above opened all issues and CR fixed.

##### Status:done
