### ISSUE TITLE
ISSUES FOUND FROM LATEST GITHUB COPY

### ISSUE THREAD

**Issue by DHIVYAARJUAN** [SSOMENSREPO/ACE-AUTOLUTION#4]
@ACCOUNTING TEAM

FIX BELOW ISSUES IMMEDIATELY

**SETTINGS DOMAIN**

1. LOCAL  SESSION NOT WORKING 

**COMPANY DETAILS**
2. COMPANY DETAILS FORM NOT SAVING(ERROR MSG SHOWING WRONGLY)

**COA**
3. SOME ACCOUNT TYPE CAN'T UPDATE

**NOTIFICATION**

4. NOTIFICATION EMAIL SETTINGS NOT WORKING PROPERLY

**CREATE DOMAIN**

**ALL FORM PDF SHOWING ISSUE LIKE THIS**
Warning: require_once(../public/mpdf571/mpdf571/mpdf.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ACE-AUTOLUTION-1.2\Create\Pdf_Job_Schedule.php on line 12

**INVOICE** 
1. invoice edit getting issue like this
Parse error: syntax error, unexpected '$rowid' (T_VARIABLE) in C:\xampp\htdocs\ACE-AUTOLUTION-1.2\Create\Form_invoice_edit.php on line 9

2. **INVOICE CREDIT NOTE NOT WORKING**

**RECEIPT**
3. RECEIPT FORM LOADED BOTH CUSTOMER AND VENDOR(NEED TO LOAD CUSTOMER OLY)

**REPORT**
1. **INCOME BY CUSTOMER** FORM HAVING ISSUE.
NEED TO GET DATAS FROM VW_INCOME_BY_CUSTOMER.

**Comment by DHIVYAARJUAN** [comment]
@accounting team

refer this ss and fix issues found by today
https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1475322253

**Comment by DHIVYAARJUAN** [comment]
issues found on 30/10/2015
https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1475322253

**Comment by DHIVYAARJUAN** [comment]
Note: Above issues should fix in premium also

**Comment by SasikalaDjeasankar** [comment]
ISSUES FOUND ON 05-11-2015 LATEST SCRIPT.

@Accounting Team:

IF FORMS ARE COMMON IN BOTH ACE AND PREMIUM PLEASE FIX IN BOTH.


SSLINK:
https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1034143739

**Comment by SasikalaDjeasankar** [comment]
##### Status:Closed
