### ISSUE TITLE
ISSUE IN ACE 

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#5]
@lalitharajendiran 

1.Why product form currency and country loading all.

In ace only sgp only shld load.

2. Successfully product added msg came , but in DT i cannt see the product

@safiyullahmohideen 

JS shld load des order in DT

@SasikalaDjeasankar 

INV shld load des order in DT

@ Balachandar

Alignment of JS pdf not good. fix it

**Comment by DHANDAPANISATTANATHAN** [comment]
@ACC TEAM,

1.Email notification not implemented in ACE.( add email id in USER PROFILE)
2.INVOICE no not implemented IN Job sheet summary.Both DT and PDF
3. One JS shld be ONE INV RESTRICT

FIX AND DELY IMMEDIATELY!

**Comment by SasikalaDjeasankar** [comment]
Issue #5

##### Status:Closed
