### ISSUE TITLE
ISSUE IN ACE ON 19/11/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#6]
# DEFECT OWNER= ACC TEAM,

# TARGET TO DELY TODAY(20/11/2015)

1. Theme Manager color LABEL incorrect. select A color B color coming -> chk nd fix all colors
2. CATEG DT -> del rec option nt wrking
3. Each Srv Pack w EXP date fr each INV shd be saved in DB, so as to send trigger notif fr each SERV EXP date per INV to ADMIN, mail to be sent one week before the EXP date!
4. 3 Levels of  SRV we need in ADD INV part, CAT,SUBCAT, PROD/SERV, so add a field ‘SERVICE before QTY. so the flow will be like:
CATEG
SUBCATEG
PROD/SERVICE
5. PRODUCTS DT missing wen u follow these steps:
	ADD PROD, ADD SRV, again gotov  ADD PROD, DT missing fr PROD..
6. Form -> ADD PROD -> Certain FIELDS r nt aligned properly
7. ALL FONTS in both projects to be increased everywhere
8. 1st ROW(4/5) ICONS to be CENTRE ALIGNED & nt LEFT ALIGNED as PER now

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

1.Cannt go back if i select others in Inv. - SKL
2.Debit note pdf not loading. - BC
3.Receipt note save showing alert. Remove it. - LL
4.Stock Take List - if no record in search showing 'undefind' - Give 'No record Found' - 
5.Expense - PDF not loading.
6.Journal Entry - Save draft not working, when Any one amt empty.
7.Payments - Save draft not working .
8.Delivery note pdf downloaing PP letter pad. - AI 

Note: if unnessary option remove.

i hope most of these issue you fixed, Dely within 1 hr

**Comment by SasikalaDjeasankar** [comment]
All issues are  fixed in above listed.  And uploaded all latest scripts in dev GCE.

In point 7 added extra option in edit for save as draft status.


# Status :Fixed

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_clarified

@SasikalaDjeasankar 

May i take all files in DEV?

**Comment by SasikalaDjeasankar** [comment]
Issue #6

##### Status:Closed
