### ISSUE TITLE
DEFECT IN ACE - 25/11/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#7]
@SasikalaDjeasankar 

1.Why responsive missed in some forms?

1. JS, INV, CUSTOMER .....

2. CHECK DEF 25/11/2015 IN THE BELOW DOC AND CLOSE

https://docs.google.com/document/d/1EhV1Y2XhRrZXNj3xCG6bIDO9u8wdUOb8WSQv5zN8QWc/edit#

3.Why role wise LOGIN form not displaying - REGRESSION. 

4.Remove edit profile in user login.

**Comment by SasikalaDjeasankar** [comment]
As per the above listed issues

1.Implemented table responsive for forms having DT/Multirow.
2.Fixed what are the CR gave on 25/11/2015 indoc.
3.It is not form side defect, in DB itself having some issue.
4.Removed edit profile for all login.



### Status :Fixed

**Comment by SasikalaDjeasankar** [comment]
Issue #7

##### Status:Closed
