### ISSUE TITLE
DEFECT IN ACE - 28/11

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#8]
FIX AND GIVE ME IMMEDIATELY;

BOTH TEAM,

1.REMOVE PDF AND EXCEL BTN IN ALL REPORTS.
2.THOSE UNCOMPLETED FORM REMOVE
3.ADD DEPARTMENT BY DEFAULT IN DB

**Comment by safiyullahmohideen** [comment]
Remove all unwnated pdf and excel, Script updated in GCE

Db side RL fixed all

**Comment by arthisena** [comment]
As per my defect i completed all and uploaded in server also.



*Regards,*

*ARTHI.K**JUNIOR WEB DEVELOPER*
*​**SSOMENS SOFTWARE DEVELOPMENT*
*04132333229 /230/231*
www.ssomens.com
[image: C:\Users\SSOMENS-003_2\Desktop\business development
material\customLogo.gif.png]

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

using client server i got the below issue in PDF.i gave SO like also to fix this.fix this today!

mPDF error: Some data has already been output to browser, can't send PDF file

http://stackoverflow.com/questions/27581179/mpdf-error-some-data-has-already-been-output-to-browser-cant-send-pdf-file

**Comment by SasikalaDjeasankar** [comment]
Issue #8

##### Status:Closed
