### ISSUE TITLE
CLIENT FEED BACK ON 30/11/2015 

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/ACE-AUTOLUTION#9]
ACC TEAM,

Check the client feedback.Change  Both ace and PP.Check with SN before implement:

Refer:
Updates - 30/11:
https://docs.google.com/document/d/120VKxeC8lrvuM740nYJMK2Jqk5IbjY3oMIquo9aHf_c/edit

I have attached back the excel on my other feedbacks. 
Refer img below: all these images in drive also

https://drive.google.com/drive/folders/0B_f0d7mdbV_UflQ0VG5FcmtpTVFrRXg2X1hScmV1VWNINjdRVHZ3ZDRDWmZqdmFPNGNLUzQ

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

FIX ALL AND DELY TODAY!

CR:

1.
a) i ll remove Dash board to salesuser. can see only JS - SALES USER
b)sales manager can approve the inv but then they cannot edit after they approve. If they wish to edit, they need to find the superuser(the boss) who can log in to edit the invoice. So that sales manager what they create they can approve but they cannot edit after it is approved. if draft they still can edit.
c) Super user can do all 

2.they do not have delivery order, they only have invoice function. So the deduction is from Invoice created. If invoice is confirmed, it will deduct, Invoice is cancelled it will return the stocks to the inventory, Invoice is unapproved and edited will make the necessary editing to the Inventory. 

Remove the deliver note form

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

When only r u going to update all opened?


I need mail configuration from DB . No hardcode.

Change and give me!

**Comment by DHIVYAARJUAN** [comment]
created config table and delivered in below link

https://github.com/SSOMENSREPO/ACE-SQL/releases/tag/v0.1

**Comment by DHANDAPANISATTANATHAN** [comment]
@safiyullahmohideen 

Change the ace service mail display name =ACE ACCOUNTING ADMIN

**Comment by DHANDAPANISATTANATHAN** [comment]
@RAJALAKSHMIRAJKUMAR 

Update in all ace db and empty db also!

Safi this one not for you!

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
Changed the ace service mail display name =ACE ACCOUNTING ADMIN

Updated in all ace db and empty db.

Status : **Done**

**Comment by SasikalaDjeasankar** [comment]
Issue #9

##### Status:Closed
